### PR TITLE
Bump cardano-node to 1.35.3-rc1

### PR DESCRIPTION
**Pull request by sevanspowell**
- Bump dependencies:
  - cardano-node to 1.35.3-rc1
  - hw-aeson to match cardano-node
  - hedgehog-extras to match cardano-node
- Update compatibility matrix.

### Comments

Changelogs:

- [API](https://github.com/input-output-hk/cardano-node/blob/release/1.35/cardano-api/ChangeLog.md)
- [CLI](https://github.com/input-output-hk/cardano-node/blob/release/1.35/cardano-cli/ChangeLog.md)
- [Node](https://github.com/input-output-hk/cardano-node/blob/release/1.35/cardano-node/ChangeLog.md)

- [Compare v1.35.3-testnetonly and v1.35.3-rc1](https://github.com/input-output-hk/cardano-node/compare/1.35.3-testnetonly...1.35.3-rc1)

### Issue Number

ADP-2123

### CODE REVIEW

**Comment by sevanspowell** [comment]
Bump of hw-aeson causes cardano-addresses to fail. Need to update cardano-addresses.

```
       last 10 log lines:
       >     Not in scope: ‘JM.toList’
       >     Module ‘HaskellWorks.Data.Aeson.Compat.Map’ does not export ‘toList’.
       >     |
       > 804 |             case JM.toList o of
       >     |                  ^^^^^^^^^
```

**Comment by sevanspowell** [comment]
UPDATE:

cardano-addresses does this:

```
import qualified HaskellWorks.Data.Aeson.Compat.Map as JM

someFn = JM.toList
```

In version v0.1.5.0 this worked fine with aeson versions < 2.0.0.0 and aeson versions > 2.0.0.0. 

In version v0.1.6.0 however, this no longer works. When compiled with versions of aeson > 2.0.0.0, we can't find toList:

       last 10 log lines:
       >     Not in scope: 'JM.toList'
       >     Module 'HaskellWorks.Data.Aeson.Compat.Map' does not export 'toList'.
       >     |
       > 804 |             case JM.toList o of
       >     |                  ^^^^^^^^^

I expect that this change in hw-aeson broke the API:

```diff
-import Data.Aeson.KeyMap as JM
+import qualified Data.Aeson.KeyMap as JM
```
https://github.com/haskell-works/hw-aeson/compare/v0.1.5.0...v0.1.6.0

But I'm not sure why it broke the API.

UPDATE:
Fixed in https://github.com/input-output-hk/cardano-addresses/pull/194.

**Comment by sevanspowell** [comment]
bors try

**Review by paweljakubas — APPROVED** [review]
LGTM, but I would wait with merging cardano-addresses, have the final commit and use it here

File: lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs [hunk 1]
```diff
@@ -3855,6 +3855,7 @@ mockProtocolParametersForBalancing = (mockProtocolParameters, nodePParams)
             Just $ Cardano.ExecutionUnits 10000000000 14000000
         , Cardano.protocolParamCollateralPercent = Just 1
         , Cardano.protocolParamMaxCollateralInputs = Just 3
+        , Cardano.protocolParamUTxOCostPerByte = Just 4310
```
Comment (jonathanknowles) [inline lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs]: Suggestion: locate the following protocol parameters together:
```hs
        , Cardano.protocolParamUTxOCostPerWord = Just 34482
        , Cardano.protocolParamUTxOCostPerByte = Just 4310
```

File: lib/shelley/src/Cardano/Wallet/Shelley/Network/Blockfrost.hs [hunk 2]
```diff
@@ -965,6 +965,7 @@ fromBlockfrostPP network pp@BF.ProtocolParams{..} = do
                     , protocolParamCollateralPercent = Just collateralPercent
                     , protocolParamMaxCollateralInputs =
                         Just $ intCast maxCollateralInputs
+                    , protocolParamUTxOCostPerByte = Just 4310
```
Comment (jonathanknowles) [inline lib/shelley/src/Cardano/Wallet/Shelley/Network/Blockfrost.hs]: Suggestion: locate this protocol parameter value next to `protocolParamUTxOCostPerWord`.

**Review by jonathanknowles — COMMENTED** [review]
Hi Sam

Just a couple of suggestions that may help readability/discoverability of minimum-UTxO-related protocol parameter values.

**Review by Anviking — APPROVED** [review]

File: lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs (hunk 1 above)
Comment (jonathanknowles) [reply lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs]: Suggestion: given that these are commonly-used test values, you could just import the values defined here:

https://github.com/input-output-hk/cardano-wallet/blob/1f72c95d081c973e492da739faeee4bdefcfd244/lib/core/src/Cardano/Wallet/Primitive/Types/MinimumUTxO/Gen.hs#L154
https://github.com/input-output-hk/cardano-wallet/blob/1f72c95d081c973e492da739faeee4bdefcfd244/lib/core/src/Cardano/Wallet/Primitive/Types/MinimumUTxO/Gen.hs#L162

File: lib/shelley/src/Cardano/Wallet/Shelley/Network/Blockfrost.hs (hunk 2 above)
Comment (jonathanknowles) [reply lib/shelley/src/Cardano/Wallet/Shelley/Network/Blockfrost.hs]: Suggestion: given that these are commonly-used test values, you could just import the values defined here:

https://github.com/input-output-hk/cardano-wallet/blob/1f72c95d081c973e492da739faeee4bdefcfd244/lib/core/src/Cardano/Wallet/Primitive/Types/MinimumUTxO/Gen.hs#L154
https://github.com/input-output-hk/cardano-wallet/blob/1f72c95d081c973e492da739faeee4bdefcfd244/lib/core/src/Cardano/Wallet/Primitive/Types/MinimumUTxO/Gen.hs#L162

File: lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs [hunk 3]
```diff
@@ -3842,7 +3846,10 @@ mockProtocolParametersForBalancing = (mockProtocolParameters, nodePParams)
         , Cardano.protocolParamPoolPledgeInfluence = 0
         , Cardano.protocolParamMonetaryExpansion = 0
         , Cardano.protocolParamTreasuryCut  = 0
-        , Cardano.protocolParamUTxOCostPerWord = Just 34482
+        , Cardano.protocolParamUTxOCostPerWord =
+            Just $ fromIntegral $ SL.unCoin testParameter_coinsPerUTxOWord_Alonzo
+        , Cardano.protocolParamUTxOCostPerByte =
+            Just $ fromIntegral $ SL.unCoin testParameter_coinsPerUTxOByte_Babbage
```
Comment (jonathanknowles) [inline lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs:3852]: 👍🏻

File: lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs [hunk 4]
```diff
@@ -3842,7 +3846,10 @@ mockProtocolParametersForBalancing = (mockProtocolParameters, nodePParams)
         , Cardano.protocolParamPoolPledgeInfluence = 0
         , Cardano.protocolParamMonetaryExpansion = 0
         , Cardano.protocolParamTreasuryCut  = 0
-        , Cardano.protocolParamUTxOCostPerWord = Just 34482
+        , Cardano.protocolParamUTxOCostPerWord =
+            Just $ fromIntegral $ SL.unCoin testParameter_coinsPerUTxOWord_Alonzo
```
Comment (jonathanknowles) [inline lib/shelley/test/unit/Cardano/Wallet/Shelley/TransactionSpec.hs:3850]: It might be possible to use `intCast` here, which checks statically that the conversion is lossless. (Instead of `fromIntegral`.)

**Comment by Anviking** [comment]
🤔 
bors r+
